#!/usr/bin/python3
d='happy new year'
print(d)
print(d[::-1])
print(d[:3])
print(d[:4])
print(d[:6])
print(d[::-3])
print(d[9:13])
name='aron rotich'
print(name)
print(len('name'))
print(name[1])
print(name[:-3])
print(name , '\n' + name)
print(name[6:12])


